// <auto-generated />
namespace E_Commerce_Platform_for_Spices.AdminPortal
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label EmailLabel;
        protected global::System.Web.UI.WebControls.TextBox EmailTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator EmailRequired;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator EmailFormat;
        protected global::System.Web.UI.WebControls.Label PasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox PasswordTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator PasswordRequired;
        protected global::System.Web.UI.WebControls.CheckBox RememberCheckBox;
        protected global::System.Web.UI.WebControls.LinkButton ForgotPasswordButton;
        protected global::System.Web.UI.WebControls.Button SignInButton;
        protected global::System.Web.UI.WebControls.Label FormMessage;
    }
}
